Store the disposable's finalizers in a station-variable before modifying
SOF3/await-std pull request #6
Opened 2021-12-11 13:54 UTC by Endermanbugzjfc

- Trying to fix #4

2022-01-23 08:17 UTC, Endermanbugzjfc commented
omg did poggit finally built this commit

2022-01-24 15:32 UTC, SOF3 requested changes

2022-01-24 15:32 UTC, SOF3 commented on src/SOFe/AwaitStd/DisposableListener.php
> +		$finalizersOfDisposable = $this->finalizers[$disposable] ?? [];
```suggestion

		$finalizersOfDisposable = $this->finalizers[$disposable] ?? [];
```

2022-01-24 15:35 UTC, SOF3 approved these changes

2022-01-24 15:35 UTC, merged